### ISSUE TITLE
Export to mysql

### ISSUE THREAD

**Issue by PH-F** [themaverik/mod_mam_export#1]
Hi There,

I installed this module, in ejabberd 17.04 and the complete archive is added to the mysql database.
However i'm not able to retrieve it.
Looks like the structure is just slightly different, or is there another step I can take to make the archive visible?

Thank you for your reply.

**Comment by themaverik** [comment]
@PH-F I forgot to patch this module, since they have integrated the export method directly in the latest version 17.06. I've updated the module. Please use the latest update and export again.

**Comment by PH-F** [comment]
Thx, it works perfect I appreciate it.
